language: python
python:
  - "2.7"

notifications:
  email:
    - jeremy.dagorn@gmail.com

before_install: bash scripts/before_install.sh
install: pip install -r requirements.txt --use-mirrors
script:
	- export PYTHONPATH=`pwd`
	- echo $PYTHONPATH
	- python test_suite.py
