language: python
python:
  - "2.7"

notifications:
  email:
    - jeremy.dagorn@gmail.com

before_install: bash scripts/before_install.sh
install: pip install -r requirements.txt --use-mirrors
script:
  - mv publishr/config.py.local publishr/config.py
  - mv publishr/tests/config.py.local publishr/tests/config.py
  - bash scripts/generate_dummy_css.sh
  - export PYTHONPATH=`pwd`
  - echo $PYTHONPATH
  - python test_suite.py
